### ISSUE TITLE
Support dynamic data?

### ISSUE THREAD

**Issue by bobbyc** [aws/amazon-ec2-metadata-mock#70]
Hi team,

I am building a 'aws-glue' development environment in my local computer. When I build the dev environment, aws-glue needs dynamic data when I use amazon-ec2-metadata-mock to similar metadata service. Do you have plan to support dynamic data, such as '/latest/dynamic/instance-identity/document' in the future release?

NOTE: I already build my own patch in my fork.

**Comment by bwagner5** [comment]
Yeah! This definitely seems like something amazon-ec2-metadata-mock would benefit from!  I believe we already serve a lot of this data from meta-data paths like `ami-id`, `instance-id`, `instance-type`, and `local-ipv4`. 

Since you've already patched in your fork, would you be willing to work on a PR for this new feature? 

Example:
```
curl 169.254.169.254/latest/dynamic/instance-identity/document
{
  "accountId" : "0123456789",
  "architecture" : "x86_64",
  "availabilityZone" : "us-east-1f",
  "billingProducts" : null,
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : null,
  "imageId" : "ami-0b69ea66ff7391e80",
  "instanceId" : "i-01234567890",
  "instanceType" : "t3.2xlarge",
  "kernelId" : null,
  "pendingTime" : "2020-04-08T16:57:10Z",
  "privateIp" : "10.0.7.10",
  "ramdiskId" : null,
  "region" : "us-east-1",
  "version" : "2017-09-30"
}%
```

**Comment by bobbyc** [comment]
@bwagner5 Thanks for your feedback. I like the idea, and I filed a PR #74 for this. Please help to review PR for me.

**Comment by brycahta** [comment]
Closing issue following ther merge of #74
